### ISSUE TITLE
如何适配手机尺寸呢

### ISSUE THREAD

**Issue by z404558** [aixinchao/HYWordClockDemo#1]
如何适配手机尺寸呢，在手机上左右没有显示全

**Comment by aixinchao** [comment]
调整字体大小 和  圆的半径 应该可以手机能显示下  




------------------ 原始邮件 ------------------
发件人: "Eric Liu"<notifications@github.com>;
发送时间: 2019年4月15日(星期一) 中午11:19
收件人: "aixinchao/HYWordClockDemo"<HYWordClockDemo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [aixinchao/HYWordClockDemo] 如何适配手机尺寸呢 (#1)




如何适配手机尺寸呢，在手机上左右没有显示全
